# Generated by Django 3.2.9 on 2021-11-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeloVendoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('contacto_telefonico', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('producto', models.CharField(max_length=30)),
            ],
        ),
    ]
